### ISSUE TITLE
Passing HtmlTag as a property to the JSX component?

### ISSUE THREAD

**Issue by ArthurTimofey** [kitajs/html#39]
Heyo!

Having great fun using this package in my project but I'm trying to use the HtmlTag types to pass as props, I would of assumed that `...rest` would do the trick but it does not seem to, The types are happy from typescript end so I am unsure why its not appending the attributes.

```tsx
type JSXKeys = keyof JSX.IntrinsicElements['div'];
type JSXValues = JSX.IntrinsicElements['div'][JSXKeys];

type ChatMessageItemProps = {
	message: string;
} & { [K in JSXKeys]?: JSXValues };

export const ChatMessageItem = html.compile(
	({ message, ...rest }: ChatMessageItemProps) => {
		console.log('went here');
		return (
			<div class="p-4" {...rest}>
				{message}
			</div>
		);
	}
);
```

And usage

```
ChatMessageItem({ message: 'token', 'sse-swap': 'token_data' })
```

Any help appriciated!

**Comment by arthurfiorette** [comment]
Hey @ArthurTimofey, due to the nature of html.compile and its [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) usage, you cannot use the spread operator inside `Html.compile` because it has to know all properties when "compiling" and the spread operator don't invote proxy methods.

If you want to keep using the compile option, you will have to specify all properties manually. Your example is a pretty small component wich won't give any speed benefits by using `Html.compile`, so I'd advise to drop it for better DX.

**Comment by arthurfiorette** [comment]
I've also improved `Html.compile` section.

https://github.com/kitajs/html/tree/master#compiling-html

**Comment by ArthurTimofey** [comment]
@arthurfiorette thanks for clarifying that, just noticed we have the same first names haha. I suppose I am using `Html.compile` so that I can have reusable chunks of html at all times, so for this instance where I am using HTMX to render a `ChatMessageItem` where by I can modify the behaviour on this element through `...rest` in order to do interesting things like having different attributes trigger different behaviours of that chat item. I guess the correct approach would be to build html strings outside of `html` package and use `renderToString` from react in order to pass these props. Coming from react world maybe my tendency of abstracting too much is an issue but I'm just playing around for now. It's a bit of mental shift as to how things should be done.
