### ISSUE TITLE
Need a way to add scripts that doesn't get transpiled

### ISSUE THREAD

**Issue by t0mri** [kitajs/html#53]
"Hello,

I am using this (Kitajs) to transpile JSX into HTML on the server and send it to the client. The issue I face while doing that is that I can't add JavaScript (for the client-side). For example, if I just use <script>console.log("hi, mom")</script>, it just throws an error. So, to avoid this, I have to write JavaScript (for the client-side) as a string inside <script> tags.

This is how I'm doing it:
```typescript
<script>
{`
  authModal.close()
  authModal.showModal()

  authModal.addEventListener("click", (e) => {
    const dialogDimensions = authModal.getBoundingClientRect();
    if (
      e.clientX < dialogDimensions.left ||
      e.clientX > dialogDimensions right ||
      e.clientY < dialogDimensions.top ||
      e.clientY > dialogDimensions.bottom
    ) {
      authModal.remove();
    }
  });

  document.getElementById('basic-details').childNodes.forEach((field) => {
    field.addEventListener("input", () => (document.querySelector('[value=""]').style.pointerEvents = document.getElementById('basic-details').checkValidity() ? "none" : "auto"));
  });

  function saveAsCookie(e) {
    e.preventDefault();

    const name = e.target.name.value;
    const phone = e.target.phone.value;
    const city = e.target.city.value;
    const college = e.target.college.value;

    const d = new Date();
    d.setTime(d.getTime() + 60 * 60 * 1000);
    let expires = "expires=" + d.toUTCString();
    document.cookie = \`formData=\${JSON.stringify({ name, phone, city, college })}; expires=\${expires}; path=/\`;
  }
`}
</script>
```
I'm doing this without syntax highlighting or IntelliSense. Is there a better way?

**Comment by arthurfiorette** [comment]
Hey, this is kindly what you are suposed to do so. Without template strings, `{` are interpreted and you cannot write raw js. 

If you use vscode, I recommend `bierner.comment-tagged-templates` extension, which highlights the code for you:

![image](https://github.com/kitajs/html/assets/47537704/9df38544-07b3-4484-a24c-1ef787d94e65)

Otherwise, I'd just write it into a `script.js` file, validate/parse it with your tools as you would do as any other javascript file and use it this way:

```jsx
const SCRIPT = fs.readFileSync('scripts.js', 'utf-8');
html = <script>{SCRIPT}</script>;
```
