### ISSUE TITLE
Avoid escaping hx-vals

### ISSUE THREAD

**Issue by adicco** [kitajs/html#54]
Thank you for this great plugin, which I have been using successfully on a Bun/Elysia/HTMX stack. I have not managed yet to use HTMX's [hx-vals](https://htmx.org/attributes/hx-vals/) as attributes are encoded and so this mangles the output hx-vals attribute:

```
<div 
hx-swap="outerHTML"
hx-target="closest div"
hx-post="/edit/current_request/del_item/y5ktrpj4euvzfy0kr8cob0ji"
hx-vals="{&quot;type&quot;:&quot;list&quot;}"></div>
```

 Would there be a way to have some kind of "unsafe" mode for some attributes whereby their values could be raw? Thank you!

**Comment by arthurfiorette** [comment]
Hey @adicco, what's your usecase for this? The only character escaped inside attributes are `"`, which should be escaped even in your usecase, otherwise your json would break out the html:

![image](https://github.com/kitajs/html/assets/47537704/1fe26a6b-efc0-40a0-b80f-83d65045913c)

As you can simply test out, when getting the raw attribute value inside javascript, the `&quot;` character is interpreted correctly and can be safely parseable:

![image](https://github.com/kitajs/html/assets/47537704/bfb351a5-c9c1-4ab1-bcc6-b9efa3f4bc3e)

**Comment by adicco** [comment]
@arthurfiorette Thanks for looking into this. My use case [is this](https://htmx.org/attributes/hx-vals/) but you make a good point regarding quotes breaking the HTML. 

Would it then be possible to use single quotes for certain attributes such as hx-vals?

**Comment by arthurfiorette** [comment]
@adicco, does HTMX breaks when parsing `{&quot;type&quot;:&quot;list&quot;}`?

**Comment by arthurfiorette** [comment]
Actually, I think this would be a good PR to htmx

**Comment by adicco** [comment]
@arthurfiorette Thanks, will look on the HTMX side of things, and will keep you posted.
